### ISSUE TITLE
Project Maintenance

### ISSUE THREAD

**Issue by simibac** [PokeMate/image-generator#1]
## User Story
As a developer, I want to have a readme and a wiki with detailed information about the setup instructions of the application so that the project can be cloned and deployed on a different machine.

## Description
- The readme explains briefly how the model can be trained, the API can be installed and deploy
- The wiki informs the people similar to the readme but in an extended form, such as the available endpoints etc.

## Tasks
- [ ] readme: instructions for training the model
- [ ] readme: instructions for setting up the environment
- [ ] readme: instructions for building and running the service with or without Docker
- [ ] readme: instructions for running the tests
- [ ] wiki: instructions for the endpoints
- [ ] .gitignore
