### ISSUE TITLE
Train model for generating new Pokemon images

### ISSUE THREAD

**Issue by simibac** [PokeMate/image-generator#2]
## User Story
As a user, I want to have a unique image for my newly mated Pokemon.

## Description
A model should be trained which can generate Pokemon images. Ideally the service should use the images of its parent Pokemons to generate a morphed version of its paretns.

## Tasks
- [x] Find or generate a collection of existing Pokemon images
- [x] Setup or clone a NN, GAN
- [x] Train a model
- [x] Export the model such that it can be integrated into a REST Api

**Comment by simibac** [comment]
This dataset might be helpful for creating a collection of all the existing Pokemon images: https://www.kaggle.com/kvpratama/pokemon-images-dataset

**Comment by simibac** [comment]
These models might be useful for generating new Pokemons. However, they do not consider the parent images. But images could be generated in advance so that the user doesn't have to wait for mating a new Pokemon as with other algorithms (such as StyleGAN). 
GANs:
- https://github.com/Zhenye-Na/pokemon-gan
- https://github.com/llSourcell/Pokemon_GAN

**Comment by simibac** [comment]
We could also use somthing like deepart an take on image of a Pokemon and apply the style of another Pokemon (https://github.com/yohannnyc/deepart)
![image](https://user-images.githubusercontent.com/15369592/77237281-ef420780-6bc6-11ea-9831-588a786542c2.png)
