### ISSUE TITLE
Exposing model with a REST Api

### ISSUE THREAD

**Issue by simibac** [PokeMate/image-generator#3]
## User Story
As a developer, I want to have an API for generating new Pokemon images so that it can be integrated as a micro service into other application.

## Description
- The model which is generated in #2 is used to build a REST Api, which can be used to query a new Pokemon image from other services. 
- The Swagger integration allows for testing the endpoints quickly.
- A Dockerfile should be provided such that it can be integrated as a micro service and scaled in future.

## Tasks
- [x] Setup a service that uses the model from #2 to generate names
- [x] Setup REST Api with a GET-route
- [x] Test the endpoint
- [x] Test the service for using the model from #2 
- [x] Integrate Swagger
- [x] Setup Dockerfile
